name: YangzomBrauen
favicon: null
layout_spectrum: 0.74392
typography_spectrum: 0.49932
title: NEWS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7ab8e3'
    - '#ffe7c6'
    - '#4d5d70'
    - '#fd9659'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
