name: YangzomBrauen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49932
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e9ee'
    - '#2d160c'
    - '#c5a379'
    - '#8f6f4f'
    - '#882d43'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
