name: YangzomBrauen
favicon: null
layout_spectrum: 0
typography_spectrum: 0.35998
title: NEWS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7ab8e3'
    - '#ffe7c6'
    - '#4d5d70'
    - '#fd9659'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
