name: YangzomBrauen
favicon: null
layout_spectrum: 0.610722292214632
typography_spectrum: 0.7955553943756968
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2094750024843961
  lightness: 0.9156761167105287
  saturation: 0.9989665623288602
  rhythmicContrast: 0.29527643718756735
purpose: []
